# This is a basic workflow to help you get started with Actions

# name: Testing

# on:
#   push:
#     branches:
#       - main
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
     
#       - uses: actions/checkout@v1

#       - name: Deploy to server
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           port: ${{ secrets.PORT }}
#           key: ${{ secrets.SSHKEY }}
#           script: "cd public_html && ./.scripts/deploy.sh"
    
